[simulation]
norms = "norm-schedule.csv"
seed = 102
startdate = 2020-01-01
iterations = 2020-06-30 # End date; Alternatively, specify the number of iterations

# The modes of the the government attitude
[calibration]
modeLiberal = 0.85
modeConservative = 0.65


# If these are set, they will be included in the file names of output files
# [output]
# descriptor = "some-description"
# nodenum = 0

[counties]
	[counties.charlottesville]
	fractionLiberal = 0.8325
	fipscode = "540"
	seed = 42
	activities = ["charlottesville_examples/usa_va_charlottesville_activity_assignment_adult_week_1_6_0.csv", "charlottesville_examples/usa_va_charlottesville_activity_assignment_child_week_1_6_0.csv"]
	households = ["charlottesville_examples/usa_va_charlottesville_household_1_6_0.csv"]
	persons = ["charlottesville_examples/usa_va_charlottesville_person_1_6_0.csv"]
	locations = ["charlottesville_examples/usa_va_charlottesville_location_assignment_week_1_6_0.csv"]
	statefile = "charlottesville_examples/start_state_ifrac0.01_sfrac0.6.csv"


	# [counties.albemarle]
	# fipscode = "003"
	# seed = 32
	# fractionLiberal = 0.624
	# activities = ["albemarle_county_1_9_0/albemarle_location_assignment_adult_1_9_0.csv", "albemarle_county_1_9_0/albemarle_location_assignment_child_1_9_0.csv"]
	# households = ["albemarle_county_1_9_0/albemarle_household_1_9_0.csv"]
	# persons = ["albemarle_county_1_9_0/albemarle_person_1_9_0.csv"]


	# [counties.fluvanna]
	# fipscode = "065"
	# fractionLiberal = 0.4535
	# activities = ["fluvanna_county_1_9_0/fluvanna_location_assignment_adult_1_9_0.csv", "fluvanna_county_1_9_0/fluvanna_location_assignment_child_1_9_0.csv"]
	# households = ["fluvanna_county_1_9_0/fluvanna_household_1_9_0.csv"]
	# persons = ["fluvanna_county_1_9_0/fluvanna_person_1_9_0.csv"]

	# [counties.louisa]
	# fipscode = "109"
	# fractionLiberal = 0.3775
	# activities = ["louisa_county_1_9_0/louisa_location_assignment_adult_1_9_0.csv", "louisa_county_1_9_0/louisa_location_assignment_child_1_9_0.csv"]
	# households = ["louisa_county_1_9_0/louisa_household_1_9_0.csv"]
	# persons = ["louisa_county_1_9_0/louisa_person_1_9_0.csv"]

	[counties.goochland]
	fipscode = "075"
	fractionLiberal = 0.3755
	seed = 68
	activities = ["goochland_county_1_9_0/goochland_location_assignment_adult_1_9_0.csv", "goochland_county_1_9_0/goochland_location_assignment_child_1_9_0.csv"]
	households = ["goochland_county_1_9_0/goochland_household_1_9_0.csv"]
	persons = ["goochland_county_1_9_0/goochland_person_1_9_0.csv"]

	# [counties.hanover]
	# fipscode = "085"
	# seed = 78
	# fractionLiberal = 0.3385
	# activities = ["hanover_county_1_9_0/hanover_location_assignment_adult_1_9_0.csv", "hanover_county_1_9_0/hanover_location_assignment_child_1_9_0.csv"]
	# households = ["hanover_county_1_9_0/hanover_household_1_9_0.csv"]
	# persons = ["hanover_county_1_9_0/hanover_person_1_9_0.csv"]

	# [counties.henrico]
	# fipscode = "087"
	# seed = 114
	# fractionLiberal = 0.604
	# activities = ["henrico_county_1_9_0/henrico_location_assignment_adult_1_9_0.csv", "henrico_county_1_9_0/henrico_location_assignment_child_1_9_0.csv"]
	# households = ["henrico_county_1_9_0/henrico_household_1_9_0.csv"]
	# persons = ["henrico_county_1_9_0/henrico_person_1_9_0.csv"]

	# [counties.richmondcity]
	# fipscode = "760"
	# seed = 54
	# fractionLiberal = 0.8175
	# activities = ["richmondcity_county_1_9_0/richmondcity_location_assignment_adult_1_9_0.csv", "richmondcity_county_1_9_0/richmondcity_location_assignment_child_1_9_0.csv"]
	# households = ["richmondcity_county_1_9_0/richmondcity_household_1_9_0.csv"]
	# persons = ["richmondcity_county_1_9_0/richmondcity_person_1_9_0.csv"]

	##### The following is not in the list of selected counties, so comment out for real run
	[counties.richmondcity]
	fipscode = "760"
	seed = 54
	fractionLiberal = 0.8175
	activities = ["nelson_county_examples/nelson_county_located_activities_adult.csv", "nelson_county_examples/nelson_county_located_activities_child.csv"]
	households = ["nelson_county_examples/nelson_county_household.csv"]
	persons = ["nelson_county_examples/nelson_county_person.csv"]
