[simulation]
norms = "norm-schedule.csv"
startdate = 2020-03-01
iterations = 2020-06-28 # End date; Alternatively, specify the number of iterations
diseasemodel = "../../../../pansim/tests/disease_models/seiar.toml"

# Optionally, specify a list of files making up the household assignments, with headers "hid,is_liberal", using 1 for true
# and 0 for false
# This value can also be specified for each county seperately in the [counties] list using the same key.
# If specified, an assignment must be present for EACH HOUSEHOLD (in the county)

# householdVotingAssignment = ['votingassignment.csv']

[infectionseeding]
perday = 5
days = 5
additional_every_other_days = 3
additional_every_other_days_num = 1

[counties]
	[counties.charlottesville]
	fractionLiberal = 0.8325
	fipscode = 540
	# seed = 42
	activities = ["charlottesville_examples/usa_va_charlottesville_activity_assignment_adult_week_1_6_0.csv", "charlottesville_examples/usa_va_charlottesville_activity_assignment_child_week_1_6_0.csv"]
	households = ["charlottesville_examples/usa_va_charlottesville_household_1_6_0.csv"]
	persons = ["charlottesville_examples/usa_va_charlottesville_person_1_6_0.csv"]
	locations = ["charlottesville_examples/usa_va_charlottesville_location_assignment_week_1_6_0.csv"]