#savestate = true

[simulation]
norms = "norm-schedule.csv"
startdate = 2020-03-01
#iterations = 2020-06-28 # End date; Alternatively, specify the number of iterations
diseasemodel = "../../../../pansim/tests/disease_models/seiar.toml"
seed = 42

# Optionally, specify a list of files making up the household assignments, with headers "hid,is_liberal", using 1 for true
# and 0 for false
# This value can also be specified for each county seperately in the [counties] list using the same key.
# If specified, an assignment must be present for EACH HOUSEHOLD (in the county)

# householdVotingAssignment = ['votingassignment.csv']

[infectionseeding]
perday = 5
days = 5
additional_every_other_days = 3
additional_every_other_days_num = 1

[counties]
	 [counties.nelson]
	 fipscode = 125
#	 seed = 54
	 fractionLiberal = 0.8175
	 activities = ["nelson_county_examples/nelson_county_located_activities_adult.csv", "nelson_county_examples/nelson_county_located_activities_child.csv"]
	 households = ["nelson_county_examples/nelson_county_household.csv"]
	 persons = ["nelson_county_examples/nelson_county_person.csv"]
	 locationDesignations = ["nelson_county_examples/location_designation.csv"]

