[simulation]
norms = "norm-schedule.csv"
startdate = 2020-03-01
iterations = 2020-06-28 # End date; Alternatively, specify the number of iterations
diseasemodel = "../../../../pansim/tests/disease_models/seiar.toml"

# Optionally, specify a list of files making up the household assignments, with headers "hid,is_liberal", using 1 for true
# and 0 for false
# This value can also be specified for each county seperately in the [counties] list using the same key.
# If specified, an assignment must be present for EACH HOUSEHOLD (in the county)

# householdVotingAssignment = ['votingassignment.csv']

[infectionseeding]
perday = 5
days = 5
additional_every_other_days = 3
additional_every_other_days_num = 1

[counties]
	 [counties.goochland]
	 fipscode = 75
	 fractionLiberal = 0.3755
#	 seed = 68
	 activities = ["goochland_county_1_9_0/goochland_location_assignment_adult_1_9_0.csv", "goochland_county_1_9_0/goochland_location_assignment_child_1_9_0.csv"]
	 households = ["goochland_county_1_9_0/goochland_household_1_9_0.csv"]
	 persons = ["goochland_county_1_9_0/goochland_person_1_9_0.csv"]
